"""Curated (hand-approved) topic page configs. Each book: (year_key, title, author, tag)."""

SEAL = 'assets/badges/web/seal-black.png'
K = 'Best Books Roundups'

CURATED = {
    'entrepreneurs': {
        'slug': 'best-books-for-entrepreneurs.html',
        'kicker': K,
        'h1': 'The Best Books For <br>Entrepreneurs Of <br>The Past Decade',
        'title': 'The Best Books For Entrepreneurs of the Past Decade | Non-Obvious Book Awards',
        'meta': ('The best books for entrepreneurs and startup founders of the past decade — chosen from more '
                 'than 800 books honored by the Non-Obvious Book Awards since 2014.'),
        'intro': ('From more than 800 books honored across a decade of the Non-Obvious Book Awards, these are '
                  'the ones we most recommend to founders and builders: on starting up, raising money, '
                  'negotiating, staying small on purpose, and surviving the messy middle.'),
        'badge': SEAL,
        'books': [
            ('2024', 'Pivot or Die', 'Gary Shapiro', 'Longlist'),
            ('2023', 'I Hope You Fail', 'Pinky Cole', 'Longlist'),
            ('2022', 'The Power Law', 'Sebastian Mallaby', 'Longlist'),
            ('2022', 'The Founders', 'Jimmy Soni', 'Longlist'),
            ('2021', 'Backable', 'Suneel Gupta', 'Shortlist'),
            ('2019', 'Company of One', 'Paul Jarvis', 'Longlist'),
            ('2019', 'Loonshots', 'Safi Bahcall', 'Shortlist'),
            ('2018', 'The Messy Middle', 'Scott Belsky', 'Longlist'),
            ('2018', 'Lost and Founder', 'Rand Fishkin', 'Longlist'),
            ('2017', 'Entrepreneurial You', 'Dorie Clark', 'Shortlist'),
            ('2016', 'Originals', 'Adam Grant', 'Shortlist'),
            ('2016', 'Never Split the Difference', 'Chris Voss', 'Shortlist'),
            ('2014', 'Hooked', 'Nir Eyal', 'Shortlist'),
        ],
        'blurbs': {
            'pivotordie': 'Consumer Technology Association CEO Gary Shapiro has watched thousands of companies rise and fall through CES: here he distills why the ability to pivot is the defining survival skill of any venture.',
            'ihopeyoufail': 'Slutty Vegan founder Pinky Cole flips every failure in her improbable rise into fuel: a raw, energizing playbook for entrepreneurs who will inevitably hit the wall.',
            'thepowerlaw': 'Sebastian Mallaby&rsquo;s definitive history of venture capital: how a handful of believers in outlier bets built the machine that finances nearly every startup dream.',
            'thefounders': 'Jimmy Soni&rsquo;s deeply reported story of the PayPal mafia, from Musk and Thiel to Levchin, and the improbable beginnings of the network that shaped two decades of tech.',
            'backable': 'Suneel Gupta went from serial rejection to raising millions, and reverse-engineered why: people don&rsquo;t back ideas, they back people who make them believe. A founder&rsquo;s guide to being backable.',
            'companyofone': 'Paul Jarvis makes the liberating case that staying small is a strategy, not a failure: essential reading for every bootstrapper and solo founder.',
            'loonshots': 'Physicist-entrepreneur Safi Bahcall explains why organizations kill their wildest ideas, and the structures that let &ldquo;loonshots&rdquo; survive long enough to change the world.',
            'themessymiddle': 'Behance founder Scott Belsky maps the long, volatile stretch between starting and finishing that nobody talks about, and how to endure the lows and optimize the highs.',
            'lostandfounder': 'Moz founder Rand Fishkin&rsquo;s painfully honest field guide to startups: the anti-hype book every founder should read before raising a dollar.',
            'entrepreneurialyou': 'Dorie Clark&rsquo;s practical blueprint for building multiple income streams around your expertise: the book that launched a thousand portfolio careers.',
            'originals': 'Adam Grant on how non-conformists move the world: when to trust your instincts, how to champion new ideas, and why originality can be cultivated.',
            'neversplitthedifference': 'Former FBI lead hostage negotiator Chris Voss brings life-or-death negotiation tactics to business: arguably the most useful negotiation book ever written.',
            'hooked': 'Nir Eyal&rsquo;s four-step model for building habit-forming products: the framework behind a generation of product design.',
        },
    },
    'ai': {
        'slug': 'best-ai-books.html',
        'kicker': K,
        'h1': 'The Best Books On <br>Artificial <br>Intelligence',
        'title': 'The Best Books On Artificial Intelligence | Non-Obvious Book Awards',
        'meta': ('The best books on artificial intelligence — the AI books honored by the Non-Obvious Book '
                 'Awards, from AI Superpowers to Brave New Words, chosen from 800+ award entries.'),
        'intro': ('Artificial intelligence went from a niche topic to the defining story of our era, and '
                  'our awards lists tracked it the whole way. These are the best books on AI we have honored: '
                  'the optimists, the skeptics, the builders and the investigators.'),
        'badge': SEAL,
        'books': [
            ('2025', 'If Anyone Builds It, Everyone Dies', 'Eliezer Yudkowsky and Nate Soares', 'Longlist'),
            ('2025', 'Raising AI', 'De Kai', 'Longlist'),
            ('2024', 'Brave New Words', 'Salman Khan', 'Most Important Winner'),
            ('2024', 'The Worlds I See', 'Fei-Fei Li', 'Longlist'),
            ('2024', 'Genesis', 'Eric Schmidt', 'Longlist'),
            ('2024', 'The Singularity Is Nearer', 'Ray Kurzweil', 'Longlist'),
            ('2024', 'The Algorithm', 'Hilke Schellmann', 'Longlist'),
            ('2023', 'Unmasking AI', 'Joy Buolamwini', 'Shortlist'),
            ('2023', 'The Coming Wave', 'Mustafa Suleyman with Michael Bhaskar', 'Longlist'),
            ('2023', 'What Is ChatGPT Doing', 'Stephen Wolfram', 'Longlist'),
            ('2023', 'Your Face Belongs to Us', 'Kashmir Hill', 'Longlist'),
            ('2021', 'Futureproof', 'Kevin Roose', 'Shortlist'),
            ('2019', 'A Human Algorithm', 'Flynn Coleman', 'Longlist'),
            ('2018', 'AI Superpowers', 'Kai-Fu Lee', 'Longlist'),
        ],
        'blurbs': {
            'ifanyonebuildsiteveryonedies': 'The starkest case yet against racing to superintelligence. Yudkowsky and Soares argue, without hedging, that building smarter-than-human AI on our current path ends badly for everyone.',
            'raisingai': 'AI pioneer De Kai reframes our relationship with artificial intelligence as parenting: we are raising AI on our behavior, so we had better model well.',
            'bravenewwords': 'Khan Academy founder Salman Khan&rsquo;s hopeful, credible map of how AI will transform education. Our Most Important Book of 2024.',
            'theworldsisee': 'Fei-Fei Li&rsquo;s luminous memoir of immigrating to America and helping invent modern AI, and her case for keeping humanity at its center.',
            'genesis': 'Eric Schmidt and co-authors on how AI reshapes power, statecraft and the human spirit: a geopolitical briefing for the intelligence age.',
            'thesingularityisnearer': 'Ray Kurzweil returns to his famous prediction with two decades of evidence, and argues the merge between humans and machines is closer than you think.',
            'thealgorithm': 'Investigative journalist Hilke Schellmann exposes the AI already deciding who gets hired, promoted and fired, often with no idea what it&rsquo;s doing.',
            'unmaskingai': 'Algorithmic Justice League founder Joy Buolamwini&rsquo;s account of discovering bias baked into facial recognition, and her fight to make AI accountable.',
            'thecomingwave': 'DeepMind co-founder Mustafa Suleyman on the containment problem: what happens when AI and synthetic biology outrun our ability to control them.',
            'whatischatgptdoing': 'Stephen Wolfram&rsquo;s remarkably clear explanation of what large language models actually do: still the best technical primer for curious non-engineers.',
            'yourfacebelongstous': 'Kashmir Hill&rsquo;s gripping investigation of Clearview AI and the secretive startup that ended anonymity: privacy journalism at its best.',
            'futureproof': 'Kevin Roose&rsquo;s nine rules for being human in the age of automation: practical optimism for anyone worried about the robots.',
            'ahumanalgorithm': 'Flynn Coleman&rsquo;s early, prescient exploration of how artificial intelligence forces us to redefine what makes us human, years before the ChatGPT era.',
            'aisuperpowers': 'Kai-Fu Lee&rsquo;s influential account of the AI race between Silicon Valley and China: the book that framed the geopolitics of AI.',
        },
    },
    'marketing': {
        'slug': 'best-marketing-books.html',
        'kicker': K,
        'h1': 'The Best Marketing <br>Books Of The <br>Past Decade',
        'title': 'The Best Marketing Books of the Past Decade | Non-Obvious Book Awards',
        'meta': ('The best marketing books of the past decade — the marketing, branding and persuasion books '
                 'honored by the Non-Obvious Book Awards since 2014.'),
        'intro': ('Marketing books were where the Non-Obvious Book Awards began, and across a decade of '
                  'lists we have honored the very best on branding, persuasion, storytelling and why things '
                  'catch on. These are the ones that still shape how the best marketers think.'),
        'badge': SEAL,
        'books': [
            ('2025', 'The Strategic Enemy', 'Laura Ries', 'Longlist'),
            ('2024', 'This Is Strategy', 'Seth Godin', 'Longlist'),
            ('2023', 'Magic Words', 'Jonah Berger', 'Longlist'),
            ('2023', 'For the Culture', 'Marcus Collins', 'Longlist'),
            ('2022', 'Influence Is Your Superpower', 'Zoe Chance', 'Longlist'),
            ('2020', 'The Catalyst', 'Jonah Berger', 'Longlist'),
            ('2019', 'Junior', 'Thomas Kemeny', 'Most Entertaining Winner'),
            ('2019', 'Stories That Stick', 'Kindra Hall', 'Longlist'),
            ('2019', 'Alchemy', 'Rory Sutherland', 'Shortlist'),
            ('2018', 'This Is Marketing', 'Seth Godin', 'Longlist'),
            ('2018', 'Talk Triggers', 'Jay Baer and Daniel Lemin', 'Shortlist'),
            ('2017', 'Hit Makers', 'Derek Thompson', 'Shortlist'),
            ('2017', 'Your Ad Ignored Here', 'Tom Fishburne', 'Shortlist'),
            ('2016', 'Small Data', 'Martin Lindstrom', 'Most Shareable Winner'),
            ('2016', 'Invisible Influence', 'Jonah Berger', 'Shortlist'),
            ('2014', 'Everybody Writes', 'Ann Handley', 'Most Useful Winner'),
        ],
        'blurbs': {
            'thestrategicenemy': 'Positioning heir Laura Ries argues every great brand needs an enemy: a sharp modern update to the playbook her father helped invent.',
            'thisisstrategy': 'Seth Godin distills a lifetime of thinking into a book about systems, games and time: strategy for people who want to make change happen.',
            'magicwords': 'Jonah Berger reveals the specific words that convince, engage and persuade: backed by natural language research on millions of interactions.',
            'fortheculture': 'Marcus Collins, the strategist behind campaigns for Beyonc&eacute; and McDonald&rsquo;s, on why culture is the most powerful force in marketing, and how brands earn a place in it.',
            'influenceisyoursuperpower': 'Yale professor Zoe Chance turns her famous MBA course into a warm, science-backed guide to becoming more influential without being manipulative.',
            'thecatalyst': 'Jonah Berger flips persuasion on its head: stop pushing harder and start removing the barriers that keep people from changing their minds.',
            'junior': 'Thomas Kemeny&rsquo;s irreverent, genuinely useful guide to making it in advertising. Our Most Entertaining Book of 2019, and the funniest career book we&rsquo;ve ever honored.',
            'storiesthatstick': 'Kindra Hall&rsquo;s four essential story frameworks for business: the practical bridge between &ldquo;storytelling matters&rdquo; and actually doing it.',
            'alchemy': 'Ogilvy vice chairman Rory Sutherland&rsquo;s gleeful case for magic over logic: why the irrational ideas are so often the ones that work.',
            'thisismarketing': 'Seth Godin&rsquo;s modern manifesto: marketing as the generous act of helping people solve their problems: the antidote to interruption-era thinking.',
            'talktriggers': 'Jay Baer and Daniel Lemin show how to build operational differentiators that customers can&rsquo;t stop talking about: word of mouth, engineered on purpose.',
            'hitmakers': 'Derek Thompson&rsquo;s science of popularity: why some products and ideas take off while equally good ones vanish. Distribution has never been explained better.',
            'youradignoredhere': 'Marketoonist Tom Fishburne skewers marketing&rsquo;s absurdities in cartoons that are funny because they&rsquo;re true, and wiser than most strategy decks.',
            'smalldata': 'Brand detective Martin Lindstrom shows how tiny human clues, like a worn sneaker or a fridge magnet, reveal desires that big data completely misses.',
            'invisibleinfluence': 'Jonah Berger on the hidden social forces that shape every choice we make, including the ones we&rsquo;re sure we made on our own.',
            'everybodywrites': 'Ann Handley&rsquo;s field guide to creating ridiculously good content. Our Most Useful Book winner, and still the standard for anyone who writes for business.',
        },
    },
    'productivity': {
        'slug': 'best-productivity-books.html',
        'kicker': K,
        'h1': 'The Best Productivity <br>Books Of The <br>Past Decade',
        'title': 'The Best Productivity Books of the Past Decade | Non-Obvious Book Awards',
        'meta': ('The best productivity books of the past decade — the books on habits, focus and getting '
                 'things done honored by the Non-Obvious Book Awards since 2014.'),
        'intro': ('A decade of our award lists produced a small shelf of books that actually change how people '
                  'work: on habits, focus, timing, learning and doing less, better. These are the '
                  'productivity books we keep recommending, year after year.'),
        'badge': SEAL,
        'books': [
            ('2025', 'Reset', 'Dan Heath', 'Longlist'),
            ('2024', 'Slow Productivity', 'Cal Newport', 'Longlist'),
            ('2024', 'Uptime', 'Laura Mae Martin', 'Longlist'),
            ('2023', 'Clear Thinking', 'Shane Parrish', 'Longlist'),
            ('2023', 'The PARA Method', 'Tiago Forte', 'Longlist'),
            ('2022', 'Stolen Focus', 'Johann Hari', 'Most Important Winner'),
            ('2021', 'Subtract', 'Leidy Klotz', 'Shortlist'),
            ('2019', 'Good Habits, Bad Habits', 'Wendy Wood', 'Longlist'),
            ('2019', 'Digital Minimalism', 'Cal Newport', 'Longlist'),
            ('2019', 'Indistractable', 'Nir Eyal', 'Longlist'),
            ('2019', 'Ultralearning', 'Scott H. Young', 'Shortlist'),
            ('2018', 'Atomic Habits', 'James Clear', 'Shortlist'),
            ('2018', 'When', 'Daniel H. Pink', 'Shortlist'),
            ('2017', 'Finish', 'Jon Acuff', 'Longlist'),
        ],
        'blurbs': {
            'reset': 'Dan Heath on finding the leverage points where a little effort changes everything: how to get unstuck and make work actually work.',
            'slowproductivity': 'Cal Newport&rsquo;s antidote to pseudo-productivity: do fewer things, work at a natural pace, and obsess over quality.',
            'uptime': 'Google&rsquo;s executive productivity advisor Laura Mae Martin shares the system she teaches the company&rsquo;s leaders: calm, practical and immediately usable.',
            'clearthinking': 'Farnam Street&rsquo;s Shane Parrish on mastering the ordinary moments that determine extraordinary outcomes: judgment as a trainable skill.',
            'theparamethod': 'Tiago Forte&rsquo;s elegantly simple system for organizing your entire digital life: four folders that end the chaos.',
            'stolenfocus': 'Johann Hari&rsquo;s investigation into why the world stopped paying attention. Our Most Important Book of 2022, and the deepest treatment of focus ever honored on our lists.',
            'subtract': 'Engineer Leidy Klotz on the untapped science of less: why our instinct is always to add, and what becomes possible when we subtract instead.',
            'goodhabitsbadhabits': 'Habit science&rsquo;s leading researcher Wendy Wood explains what forty years of evidence actually says about how habits form and break.',
            'digitalminimalism': 'Cal Newport&rsquo;s philosophy for reclaiming attention in a noisy world: the book that launched a thousand digital declutters.',
            'indistractable': 'Hooked author Nir Eyal turns his knowledge of habit-forming tech against distraction itself: how to control your attention and choose your life.',
            'ultralearning': 'Scott Young, who completed MIT&rsquo;s computer science curriculum in a year on his own, shares the strategy of aggressive self-directed learning.',
            'atomichabits': 'James Clear&rsquo;s modern classic on how tiny changes compound into remarkable results: the best-selling productivity book of its generation, honored on our 2018 shortlist.',
            'when': 'Daniel Pink turns timing into a science, showing when to work, when to break and when to switch, and proves that when you do things matters as much as what you do.',
            'finish': 'Jon Acuff&rsquo;s funny, liberating case that perfectionism, not laziness, is why we don&rsquo;t finish things, and how to beat it.',
        },
    },
    'memoirs': {
        'slug': 'best-business-memoirs.html',
        'kicker': K,
        'h1': 'The Best Business <br>Memoirs Of The <br>Past Decade',
        'title': 'The Best Business Memoirs of the Past Decade | Non-Obvious Book Awards',
        'meta': ('The best business memoirs of the past decade — first-person stories from founders and CEOs '
                 'honored by the Non-Obvious Book Awards since 2014.'),
        'intro': ('The best business books are sometimes the ones where somebody lived it. From a decade of our '
                  'award lists, these are the memoirs we most recommend: founders, CEOs and insiders '
                  'telling the truth about what building, leading and surviving really looks like.'),
        'badge': SEAL,
        'books': [
            ('2025', 'Careless People', 'Sarah Wynn-Williams', 'Most Shareable Winner'),
            ('2025', 'Bag Man', 'Lew Frankfort', 'Longlist'),
            ('2025', 'Change the Recipe', 'José Andrés with Richard Wolffe', 'Longlist'),
            ('2023', 'Turnaround Time', 'Oscar Munoz', 'Longlist'),
            ('2023', 'Black Founder', 'Stacy Spikes', 'Longlist'),
            ('2021', 'Becoming Trader Joe', 'Joe Coulombe with Patty Civalleri', 'Longlist'),
            ('2021', 'Play Nice But Win', 'Michael Dell', 'Longlist'),
            ('2019', 'This Is Not a T-Shirt', 'Bobby Hundreds', 'Longlist'),
            ('2019', "It's How We Play the Game", 'Ed Stack', 'Longlist'),
            ('2019', 'Wise Guy', 'Guy Kawasaki', 'Longlist'),
            ('2018', 'Imagine It Forward', 'Beth Comstock', 'Longlist'),
            ('2017', 'Reset', 'Ellen Pao', 'Longlist'),
            ('2017', 'Hit Refresh', 'Satya Nadella', 'Most Shareable Winner'),
            ('2016', 'Disrupted', 'Dan Lyons', 'Most Entertaining Winner'),
        ],
        'blurbs': {
            'carelesspeople': 'Sarah Wynn-Williams&rsquo;s explosive insider memoir of life among Facebook&rsquo;s leadership. Our Most Shareable Book of 2025, and the book everyone in tech spent the year talking about.',
            'bagman': 'Lew Frankfort&rsquo;s account of taking Coach from a $6 million family workshop to a global luxury powerhouse: a masterclass in brand-building told first-hand.',
            'changetherecipe': 'Chef Jos&eacute; Andr&eacute;s serves up the lessons of a life spent cooking, building restaurants and feeding people in crisis: generosity as a business philosophy.',
            'turnaroundtime': 'Oscar Munoz&rsquo;s story of turning around United Airlines while surviving a heart transplant: leadership under the most literal pressure imaginable.',
            'blackfounder': 'MoviePass founder Stacy Spikes on building companies as a Black founder in tech and Hollywood: candid about the doors that opened, and the ones that didn&rsquo;t.',
            'becomingtraderjoe': 'Joe Coulombe&rsquo;s own account of inventing America&rsquo;s most beloved grocery store: contrarian retail wisdom from the man who did everything differently.',
            'playnicebutwin': 'Michael Dell&rsquo;s unvarnished telling of the fights that defined his company: going private, battling Carl Icahn, and betting the business twice.',
            'thisisnotatshirt': 'Bobby Hundreds on building streetwear brand The Hundreds: the definitive book on community-first brand building, from someone who lived it.',
            'itshowweplaythegame': 'Dick&rsquo;s Sporting Goods CEO Ed Stack on building a retail giant, and the decision to pull assault-style rifles off his shelves, whatever it cost.',
            'wiseguy': 'Guy Kawasaki&rsquo;s life in stories, from evangelizing the Macintosh to surfing at sixty, told with the warmth and candor of tech&rsquo;s original evangelist.',
            'imagineitforward': 'Beth Comstock on two decades of championing change inside GE: an honest look at what innovation actually costs inside a giant company.',
            'reset': 'Ellen Pao&rsquo;s account of her discrimination suit against Kleiner Perkins and what it revealed about Silicon Valley: the memoir that helped spark tech&rsquo;s reckoning.',
            'hitrefresh': 'Satya Nadella&rsquo;s inside account of transforming Microsoft by putting empathy at the center of one of the world&rsquo;s most powerful companies.',
            'disrupted': 'Dan Lyons&rsquo;s riotous memoir of going from Newsweek to a tech startup at age 50: still the funniest and sharpest book ever written about startup culture.',
        },
    },
}

CURATED['southasian'] = {
    'slug': 'best-books-south-asian-authors.html',
    'kicker': 'Best Books Roundups',
    'h1': 'Best Award Winning <br>Business Books From <br>South Asian Authors',
    'title': 'Best Award Winning Business Books From South Asian Authors | Non-Obvious Book Awards',
    'meta': ('The best award-winning business and non-fiction books by South Asian authors, honored by the '
             'Non-Obvious Book Awards since 2014, listed alphabetically by author.'),
    'intro': ('A decade of the Non-Obvious Book Awards has honored an extraordinary group of South Asian '
              'authors, from CEOs and surgeons general to linguists, economists and entrepreneurs. Collected '
              'here in one reading list, alphabetically by author: every one of their honored books.'),
    'badge': 'assets/badges/web/seal-black.png',
    'books': [
        ('2018', 'Belong', 'Radha Agrawal', 'Longlist'),
        ('2024', 'Nuts and Bolts', 'Roma Agrawal', 'Longlist'),
        ('2022', 'Go Back to Where You Came From', 'Wajahat Ali', 'Longlist'),
        ('2024', 'How to Win Friends and Influence Fungi', 'Chris Balakrishnan', 'Longlist'),
        ('2022', 'The Titanium Economy', 'Asutosh Padhi and Gaurav Batra', 'Longlist'),
        ('ideapress', 'Non-Obvious Thinking', 'Rohit Bhargava', '!Published By Ideapress (Not Eligible For Awards)'),
        ('2025', 'The 5 Types of Wealth', 'Sahil Bloom', 'Longlist'),
        ('2022', 'The Newlyweds', 'Mansi Choksi', 'Longlist'),
        ('2020', 'The Person You Mean to Be', 'Dolly Chugh', 'Longlist'),
        ('2021', 'Digital Body Language', 'Erica Dhawan', 'Longlist'),
        ('2018', 'Winners Take All', 'Anand Giridharadas', 'Most Original Winner'),
        ('2025', 'How to Be Bold', 'Ranjay Gulati', 'Longlist'),
        ('2021', 'Backable', 'Suneel Gupta', 'Shortlist'),
        ('2024', 'Breaking Bias', 'Anu Gupta', 'Longlist'),
        ('2023', 'Win Every Argument', 'Mehdi Hasan', 'Longlist'),
        ('2025', 'Make Art', 'Nishant Jain', 'Longlist'),
        ('2017', 'Give Work', 'Leila Janah', 'Most Important Winner'),
        ('2021', 'Peak Mind', 'Amishi P. Jha', 'Longlist'),
        ('2024', 'Brave New Words', 'Salman Khan', 'Most Important Winner'),
        ('2021', 'Move', 'Parag Khanna', 'Most Shareable Winner'),
        ('2022', 'The 6 Phase Meditation Method', 'Vishen Lakhiani', 'Longlist'),
        ('2024', 'Wicked Problems', 'Guru Madhavan', 'Longlist'),
        ('2025', 'Uncompete', 'Ruchika T. Malhotra', 'Longlist'),
        ('2025', 'The Devil Emails at Midnight', 'Mita Mallick', 'Longlist'),
        ('2021', 'Fast Company Innovation by Design', 'Stephanie Mehta', 'Longlist'),
        ('2017', 'The Power of Onlyness', 'Nilofer Merchant', 'Longlist'),
        ('2020', 'Together', 'Vivek H. Murthy', 'Shortlist'),
        ('2017', 'Hit Refresh', 'Satya Nadella', 'Most Shareable Winner'),
        ('2025', "You're the Boss", 'Sabina Nawaz', 'Longlist'),
        ('2018', 'The Art of Gathering', 'Priya Parker', 'Shortlist'),
        ('2023', 'The Power of Saying No', 'Vanessa Patrick', 'Longlist'),
        ('2021', "You Can't Be Serious", 'Kal Penn', 'Longlist'),
        ('2023', 'The Future Is Disabled', 'Leah Lakshmi Piepzna-Samarasinha', 'Longlist'),
        ('2016', 'Persuadable', 'Al Pittampalli', 'Most Important Winner'),
        ('ideapress', 'Good Awkward', 'Henna Pryor', '!Published By Ideapress (Not Eligible For Awards)'),
        ('2022', 'The First, the Few, the Only', 'Deepa Purushothaman', 'Longlist'),
        ('2023', 'Upshift', 'Ben Ramalingam', 'Longlist'),
        ('2025', 'Defy', 'Sunita Sah', 'Longlist'),
        ('2023', 'Big Bets', 'Rajiv Shah', 'Longlist'),
        ('2023', 'The Defiant Optimist', 'Durreen Shahnaz', 'Longlist'),
        ('2024', 'Math Mind', 'Shalinee Sharma', 'Longlist'),
        ('2017', 'How To Be A Bawse', 'Lilly Singh', 'Shortlist'),
        ('2022', 'The Light We Give', 'Simran Jeet Singh', 'Longlist'),
        ('ideapress', 'Savvy', 'Shiv Singh and Rohini Luthra', '!Published By Ideapress (Not Eligible For Awards)'),
        ('ideapress', 'Why It Hurts', 'Aneesh Singla', '!Published By Ideapress (Not Eligible For Awards)'),
        ('2022', 'The Founders', 'Jimmy Soni', 'Longlist'),
        ('2025', 'Rethinking Work', 'Rishad Tobaccowala', 'Longlist'),
        ('2021', 'Useful Delusions', 'Shankar Vedantam', 'Shortlist'),
        ('2019', "The Optimist's Telescope", 'Bina Venkataraman', 'Longlist'),
        ('2020', 'Ten Lessons for a Post-Pandemic World', 'Fareed Zakaria', 'Longlist'),
        ('2024', 'Hope for Cynics', 'Jamil Zaki', 'Longlist'),
    ],
    'blurbs': {
        'belong': 'Daybreaker founder Radha Agrawal turns community-building into a practical craft: how to find your people, or gather them yourself.',
        'nutsandbolts': 'Structural engineer Roma Agrawal breaks the built world down to seven tiny inventions, from the nail to the spring, and finds wonder in each one.',
        'gobacktowhereyoucamefrom': 'Wajahat Ali answers a lifetime of that question with humor and heart: a memoir of growing up Muslim American that disarms hate by out-charming it.',
        'howtowinfriendsandinfluencefungi': 'Nerd Nite co-founder Chris Balakrishnan collects the wildest, funniest science talks from the beloved lecture series. Learning disguised as a night out.',
        'thetitaniumeconomy': 'McKinsey&rsquo;s Asutosh Padhi and Gaurav Batra spotlight the industrial-tech companies quietly powering American prosperity, hiding in plain sight.',
        'nonobviousthinking': 'From our founder, with Ben DuPont: a field guide to seeing what others miss, in four practiced habits. The thinking behind everything we do here.',
        'the5typesofwealth': 'Sahil Bloom reframes rich across five kinds of wealth: time, social, mental, physical and financial. A generational bestseller about what actually counts.',
        'thenewlyweds': 'Mansi Choksi follows three young Indian couples who married for love against every expectation, and pays close attention to what it cost them.',
        'thepersonyoumeantobe': 'NYU psychologist Dolly Chugh replaces the pressure of being a good person with the freedom of being a good-ish one: growth over perfection in the fight for fairness.',
        'digitalbodylanguage': 'Erica Dhawan decodes the signals we send on screens, where tone is invisible and a period can read as anger. Essential for the hybrid work era.',
        'winnerstakeall': 'Anand Giridharadas&rsquo;s unsparing look at how the global elite&rsquo;s world-changing efforts often protect the very systems that created the problems. A book that reframed an entire debate.',
        'howtobebold': 'Harvard Business School&rsquo;s Ranjay Gulati studies people who act with courage when it counts, and shows that boldness is a skill you can train.',
        'backable': 'Suneel Gupta went from serial rejection to raising millions, then reverse-engineered why: people don&rsquo;t back ideas, they back people who make them believe.',
        'breakingbias': 'Scientist and lawyer Anu Gupta offers research-backed practices for interrupting bias, in our minds and in our institutions, without shame or blame.',
        'wineveryargument': 'Broadcaster Mehdi Hasan shares the rhetorical craft behind his famous interviews: how to persuade, debate and hold your own in any room.',
        'makeart': 'SneakyArt creator Nishant Jain gives readers permission to draw: art as a daily practice of noticing the world, no talent prerequisite required.',
        'givework': 'Samasource founder Leila Janah argues the surest way to end global poverty is not charity but work, and shows how giving work transforms lives and communities.',
        'peakmind': 'Neuroscientist Amishi Jha shows that attention is trainable: twelve minutes a day of practice measurably strengthens focus, even under extreme stress.',
        'bravenewwords': 'Khan Academy founder Salman Khan offers the most credible early map of how AI will transform how our kids learn, and why that future is more hopeful than we fear.',
        'move': 'Parag Khanna maps the forces of climate, economics and demographics that will make the next decades the most mobile in human history, and predicts where we will all go.',
        'the6phasemeditationmethod': 'Mindvalley founder Vishen Lakhiani engineers meditation for people who hate sitting still: six phases, a few minutes, built for performance.',
        'wickedproblems': 'National Academy of Engineering&rsquo;s Guru Madhavan celebrates the unglamorous engineering mindset that untangles society&rsquo;s messiest, most wicked problems.',
        'uncompete': 'Ruchika T. Malhotra makes the case for dropping zero-sum thinking at work: collaboration, not competition, is the real advantage.',
        'thedevilemailsatmidnight': 'Mita Mallick turns years of surviving difficult bosses into a survival guide for the rest of us, without becoming the villain yourself.',
        'fastcompanyinnovationbydesign': 'Fast Company&rsquo;s Stephanie Mehta showcases two decades of design that changed business, proof that how things look and work is strategy.',
        'thepowerofonlyness': 'Nilofer Merchant names the source of every big idea: your onlyness, the singular spot where only you stand. Then she shows how to scale it.',
        'together': 'Former Surgeon General Vivek Murthy diagnoses loneliness as a public health crisis and prescribes the connection our bodies literally require.',
        'hitrefresh': 'Satya Nadella&rsquo;s inside account of transforming Microsoft by putting empathy at the center of one of the world&rsquo;s most powerful companies.',
        'youretheboss': 'Executive coach Sabina Nawaz reveals how power quietly changes managers, and the habits that keep new bosses effective and human.',
        'theartofgathering': 'Priya Parker transforms how we think about meetings, parties and conferences: every gathering needs a purpose, and most of ours have none.',
        'thepowerofsayingno': 'Professor Vanessa Patrick shares the science of empowered refusal: how to say no without guilt, and why it is a superpower at work.',
        'youcantbeserious': 'Kal Penn&rsquo;s funny, improbable memoir of chasing two careers at once: Hollywood actor and White House staffer. Proof that permission is overrated.',
        'thefutureisdisabled': 'Leah Lakshmi Piepzna-Samarasinha imagines futures built on disability justice, where care is collective and no one is disposable.',
        'persuadable': 'Al Pittampalli makes the counterintuitive case that the willingness to change your mind, being persuadable, is a defining strength of modern leadership.',
        'goodawkward': 'Executive coach Henna Pryor rebrands awkwardness as a professional asset: the discomfort you avoid is exactly where your edge lives.',
        'thefirstthefewtheonly': 'Deepa Purushothaman draws on hundreds of interviews with women of color in corporate America: the tolls, the tactics and the power in numbers.',
        'upshift': 'Ben Ramalingam studies people who perform best under pressure and distills the science of turning stress and adversity into fuel.',
        'defy': 'Psychologist Sunita Sah studies why good people comply when they long to resist, and teaches defiance as a principled, learnable skill.',
        'bigbets': 'Rockefeller Foundation president Rajiv Shah argues incrementalism is overrated: the biggest global problems yield only to big bets.',
        'thedefiantoptimist': 'Durreen Shahnaz, the first Bangladeshi woman on Wall Street&rsquo;s trading floor, tells how she built a financial platform for the world&rsquo;s excluded.',
        'mathmind': 'Zearn CEO Shalinee Sharma dismantles the myth of the math person: everyone can love math when it is taught the way brains actually learn.',
        'howtobeabawse': 'YouTube superstar Lilly Singh&rsquo;s no-excuses guide to conquering life, told with the hustle and humor that built her from bedroom vlogger to global entertainer.',
        'thelightwegive': 'Simran Jeet Singh shares Sikh wisdom for living with connection and courage in divided times. A book of practical grace.',
        'savvy': 'Shiv Singh and Rohini Luthra deliver a field guide to navigating fake companies, fake leaders and fake news, and staying clear-eyed in a post-trust era.',
        'whyithurts': 'Physician Aneesh Singla reframes pain as the body&rsquo;s essential messenger: what it is for, why we need it, and how understanding it changes treatment.',
        'thefounders': 'Jimmy Soni&rsquo;s deeply reported story of the PayPal mafia, and the improbable beginnings of the network that shaped two decades of tech.',
        'rethinkingwork': 'Advertising sage Rishad Tobaccowala maps the four seismic shifts remaking work, and how to build a career that thrives through all of them.',
        'usefuldelusions': 'Hidden Brain host Shankar Vedantam makes the counterintuitive case that self-deception is not always a bug: some illusions hold lives and societies together.',
        'theoptimiststelescope': 'Bina Venkataraman, former White House climate adviser, on why we are so bad at thinking ahead, and the tools that give foresight a fighting chance.',
        'tenlessonsforapostpandemicworld': 'Fareed Zakaria distills what the pandemic revealed about globalization, government and risk into ten clear-eyed lessons for what comes next.',
        'hopeforcynics': 'Stanford psychologist Jamil Zaki brings the evidence against cynicism: hopeful skepticism is more accurate, more useful and better for us.',
    },
}

CURATED['creativity'] = {
    'slug': 'best-creativity-books.html',
    'kicker': K,
    'h1': 'The Best Books On <br>Creativity &amp; <br>Innovation',
    'title': 'The Best Books On Creativity & Innovation | Non-Obvious Book Awards',
    'meta': ('The best books on creativity and innovation of the past decade — chosen from more than 800 '
             'books honored by the Non-Obvious Book Awards since 2014.'),
    'intro': ('Non-obvious thinking begins with seeing what others miss. From more than 800 books honored '
              'across a decade of the Non-Obvious Book Awards, these are the ones we most recommend on '
              'creativity and innovation: where ideas come from, how to champion them inside organizations '
              'that resist them, and why the most original thinkers see the world differently.'),
    'badge': SEAL,
    'books': [
        ('2025', 'Make Art', 'Nishant Jain', 'Longlist'),
        ('2025', 'The Genius Myth', 'Helen Lewis', 'Shortlist'),
        ('2024', 'Imagination', 'Ruha Benjamin', 'Shortlist'),
        ('2023', 'Awaken Your Genius', 'Ozan Varol', 'Longlist'),
        ('2022', 'How to Host a Viking Funeral', 'Kyle Scheele', 'Shortlist'),
        ('2020', 'How Design Makes the World', 'Scott Berkun', 'Shortlist'),
        ('2019', 'Alchemy', 'Rory Sutherland', 'Shortlist'),
        ('2019', 'Loonshots', 'Safi Bahcall', 'Shortlist'),
        ('2018', 'The Creative Curve', 'Allen Gannett', 'Longlist'),
        ('2018', 'Imagine It Forward', 'Beth Comstock', 'Longlist'),
        ('2017', 'Fifty Inventions That Shaped the Modern Economy', 'Tim Harford', 'Most Entertaining Winner'),
        ('2017', 'Hit Makers', 'Derek Thompson', 'Shortlist'),
        ('2016', 'Messy', 'Tim Harford', 'Most Original Winner'),
        ('2016', 'Originals', 'Adam Grant', 'Shortlist'),
        ('2016', 'Wonderland', 'Steven Johnson', 'Shortlist'),
        ('2014', 'The Doodle Revolution', 'Sunni Brown', 'Most Original Winner'),
    ],
    'blurbs': {
        'makeart': 'The artist behind SneakyArt makes the case that creativity is a practice, not a talent. Drawing the world around you, he argues, changes how you see everything in it.',
        'thegeniusmyth': 'Journalist Helen Lewis gleefully dismantles the myth of the lone genius, showing how our worship of brilliant individuals shortchanges the teams and conditions that actually produce great work.',
        'imagination': 'Princeton professor Ruha Benjamin argues that imagination is a muscle for collective change, and that the futures we build begin with the ones we dare to picture.',
        'awakenyourgenius': 'Rocket scientist turned law professor Ozan Varol offers a guide to shedding borrowed thinking, unlearning conformity and recovering the original thinker you started out as.',
        'howtohostavikingfuneral': 'Kyle Scheele asked strangers for the regrets and crazy ideas they wanted to release, then burned 20,000 of them in a cardboard Viking ship. A joyful experiment in creative permission.',
        'howdesignmakestheworld': 'Scott Berkun reveals the invisible design decisions behind everything you touch, and gives you the vocabulary to see the made world with fresh eyes.',
        'alchemy': 'Ogilvy vice chairman Rory Sutherland celebrates ideas that make no logical sense but work anyway, and explains why the opposite of a good idea can be another good idea.',
        'loonshots': 'Physicist and entrepreneur Safi Bahcall explains why organizations kill their wildest ideas, and the structures that let loonshots survive long enough to change the world.',
        'thecreativecurve': 'Allen Gannett punctures the inspiration myth with data, showing that creative hits follow a learnable curve between the familiar and the novel.',
        'imagineitforward': 'Former GE vice chair Beth Comstock delivers a candid account of championing change inside a giant company, and what it takes to give new ideas room in old institutions.',
        'fiftyinventionsthatshapedthemoderneconomy': 'Tim Harford turns the history of innovation into an addictive tour of fifty world-changing inventions, from barbed wire to the barcode. Our Most Entertaining Book of 2017.',
        'hitmakers': 'Derek Thompson decodes the science of popularity: why some creations catch on while equally good ones vanish, and what making a hit really requires.',
        'messy': 'Tim Harford builds a counterintuitive case for disorder, showing why messiness, disruption and improvisation are so often the raw ingredients of creativity. Our Most Original Book of 2016.',
        'originals': 'Adam Grant on how non-conformists move the world: when to trust your instincts, how to champion new ideas, and why originality can be cultivated.',
        'wonderland': 'Steven Johnson&rsquo;s delightful history of play, showing how amusement, games and wonder have quietly driven many of history&rsquo;s biggest breakthroughs.',
        'thedoodlerevolution': 'Sunni Brown reclaims doodling as a serious thinking tool for problem solving and idea generation. Our Most Original Book of 2014.',
    },
}

CURATED['leadership'] = {
    'slug': 'best-leadership-books.html',
    'kicker': K,
    'h1': 'The Best Leadership <br>Books Of The <br>Past Decade',
    'title': 'The Best Leadership Books Of The Past Decade | Non-Obvious Book Awards',
    'meta': ('The best leadership books of the past decade — chosen from more than 800 books honored by '
             'the Non-Obvious Book Awards since 2014.'),
    'intro': ('Leadership may be the most crowded shelf in any bookstore, which makes the great books '
              'easier to miss. From more than 800 books honored across a decade of the Non-Obvious Book '
              'Awards, these are the ones we most recommend on leading teams, building culture, and '
              'becoming the kind of boss people actually want to work for.'),
    'badge': SEAL,
    'books': [
        ('2025', "You're the Boss", 'Sabina Nawaz', 'Longlist'),
        ('2025', 'Managing Up', 'Melody Wilding', 'Longlist'),
        ('2024', 'How Leaders Learn', 'David Novak', 'Longlist'),
        ('2023', 'How Big Things Get Done', 'Bent Flyvbjerg and Dan Gardner', 'Most Important Winner'),
        ('2022', 'When Everyone Leads', "Ed O'Malley and Julia Fabris McBride", 'Longlist'),
        ('2020', 'Leading with Gratitude', 'Adrian Gostick and Chester Elton', 'Longlist'),
        ('2019', 'Nine Lies About Work', 'Marcus Buckingham and Ashley Goodall', 'Most Original Winner'),
        ('2019', 'Why Do So Many Incompetent Men Become Leaders?', 'Tomas Chamorro-Premuzic', 'Longlist'),
        ('2018', 'Powerful', 'Patty McCord', 'Longlist'),
        ('2018', 'The CEO Next Door', 'Elena Botelho and Kim Powell', 'Longlist'),
        ('2018', 'Dream Teams', 'Shane Snow', 'Longlist'),
        ('2017', 'No Ego', 'Cy Wakeman', 'Shortlist'),
        ('2016', 'Under New Management', 'David Burkus', 'Shortlist'),
        ('2016', 'Ego is the Enemy', 'Ryan Holiday', 'Shortlist'),
        ('2014', 'Leaders Eat Last', 'Simon Sinek', 'Shortlist'),
    ],
    'blurbs': {
        'youretheboss': 'Executive coach Sabina Nawaz reveals how power quietly distorts even well-meaning managers, and offers a practical reset for anyone who has become the boss they never wanted to be.',
        'managingup': 'Melody Wilding turns the overlooked half of leadership upside down: how to manage the people above you, advocate for yourself and gain influence without authority.',
        'howleaderslearn': 'Former Yum! Brands CEO David Novak profiles the habit that separates great leaders from good ones: active learning, practiced daily. Full of candid stories from the corner office.',
        'howbigthingsgetdone': 'Oxford professor Bent Flyvbjerg spent decades studying why megaprojects fail. His findings apply to everything from kitchen renovations to moon shots. Our Most Important Book of 2023.',
        'wheneveryoneleads': "Ed O'Malley and Julia Fabris McBride make the case that leadership is an activity, not a position, and show how organizations transform when everyone practices it.",
        'leadingwithgratitude': 'Adrian Gostick and Chester Elton bring the research on the most undervalued leadership behavior of all: genuine, specific, consistent gratitude.',
        'nineliesaboutwork': 'Marcus Buckingham and Ashley Goodall take a wrecking ball to workplace orthodoxy, from the annual review to the very idea of company culture. Our Most Original Book of 2019.',
        'whydosomanyincompetentmenbecomeleaders': 'Organizational psychologist Tomas Chamorro-Premuzic answers his own provocative question with data, and explains what it teaches us about choosing better leaders of every kind.',
        'powerful': 'Netflix culture architect Patty McCord distills the radical philosophy behind the famous culture deck: treat people like adults, and build teams for the future, not the past.',
        'theceonextdoor': 'Elena Botelho and Kim Powell analyzed thousands of CEO assessments and found that the leaders who reach the top look almost nothing like the myth. A data-driven map of the path.',
        'dreamteams': 'Shane Snow explores the counterintuitive science of collaboration: why great teams need friction, difference and productive tension far more than harmony.',
        'noego': 'Cy Wakeman argues that most workplace drama is self-inflicted, and shows leaders how to trade ego-driven venting for accountability and results.',
        'undernewmanagement': 'David Burkus surveys the companies quietly deleting management conventions, from unlimited vacation to abolishing email, and what happened when they did.',
        'egoistheenemy': 'Ryan Holiday draws on history and Stoic philosophy to show how ego sabotages leaders at every stage: when aspiring, when successful, and when failing.',
        'leaderseatlast': 'Simon Sinek explains why the best leaders create circles of safety, putting their people first the way the best military officers do. A modern leadership classic.',
    },
}

CURATED['communication'] = {
    'slug': 'best-communication-books.html',
    'kicker': K,
    'h1': 'The Best Books On <br>Communication &amp; <br>Storytelling',
    'title': 'The Best Books On Communication & Storytelling | Non-Obvious Book Awards',
    'meta': ('The best books on communication, storytelling, persuasion and public speaking — chosen from '
             'more than 800 books honored by the Non-Obvious Book Awards since 2014.'),
    'intro': ('Nearly every idea that matters must be communicated to survive. From more than 800 books '
              'honored across a decade of the Non-Obvious Book Awards, these are the ones we most '
              'recommend on talking, writing, listening, arguing and telling stories people remember.'),
    'badge': SEAL,
    'books': [
        ('2025', 'Talk', 'Alison Wood Brooks', 'Longlist'),
        ('2025', 'The Future of Storytelling', 'Charles Melcher', 'Most Entertaining Winner'),
        ('2024', 'Supercommunicators', 'Charles Duhigg', 'Most Shareable Winner'),
        ('2024', 'Negotiating While Black', 'Damali Peterman', 'Most Useful Winner'),
        ('2023', 'Magic Words', 'Jonah Berger', 'Longlist'),
        ('2023', 'Win Every Argument', 'Mehdi Hasan', 'Longlist'),
        ('2022', 'Good Arguments', 'Bo Seo', 'Longlist'),
        ('2022', 'I Never Thought of It That Way', 'Mónica Guzmán', 'Shortlist'),
        ('2022', 'How to Tell a Story', 'The Moth', 'Longlist'),
        ('2019', 'Writing to Persuade', 'Trish Hall', 'Most Useful Winner'),
        ('2019', 'Talking to Strangers', 'Malcolm Gladwell', 'Longlist'),
        ('2017', 'Exactly What To Say', 'Phil M. Jones', 'Most Useful Winner'),
        ('2016', 'TED Talks', 'Chris Anderson', 'Most Useful Winner'),
        ('2016', 'Illuminate', 'Nancy Duarte and Patti Sanchez', 'Shortlist'),
        ('2014', 'Everybody Writes', 'Ann Handley', 'Most Useful Winner'),
        ('2014', 'Pitch Perfect', 'Bill McGowan', 'Shortlist'),
    ],
    'blurbs': {
        'talk': 'Harvard Business School professor Alison Wood Brooks brings the science of conversation to life, showing that talking well is a learnable skill built on topics, asking, levity and kindness.',
        'thefutureofstorytelling': 'Future of StoryTelling founder Charles Melcher charts how stories are moving beyond the page and screen into immersive, interactive experiences. Our Most Entertaining Book of 2025.',
        'supercommunicators': 'Charles Duhigg decodes the people who can talk to anyone, revealing the matching principle behind every meaningful conversation. Our Most Shareable Book of 2024.',
        'negotiatingwhileblack': 'Attorney Damali Peterman delivers a masterclass in negotiation for people the classic playbooks were not written for, useful to anyone who has ever been underestimated at the table. Our Most Useful Book of 2024.',
        'magicwords': 'Jonah Berger reveals the specific words that convince, engage and persuade, backed by natural language research on millions of interactions.',
        'wineveryargument': 'Broadcaster Mehdi Hasan shares the craft behind his famously sharp interviews: how to marshal evidence, command a room, and win over an audience without losing your principles.',
        'goodarguments': 'Two-time world debate champion Bo Seo shows how the tools of competitive debate can make our everyday disagreements more productive, and even bring people closer.',
        'ineverthoughtofitthatway': 'Journalist Mónica Guzmán offers a hopeful, practical guide to genuinely curious conversations across political divides, starting with the people you love.',
        'howtotellastory': 'The team behind The Moth distills 25 years of the world&rsquo;s best true stories into a warm, practical guide to finding, shaping and telling your own.',
        'writingtopersuade': 'Former New York Times op-ed editor Trish Hall spent years deciding which arguments made the cut. Here she shares exactly what makes writing change minds. Our Most Useful Book of 2019.',
        'talkingtostrangers': 'Malcolm Gladwell investigates why our tools for making sense of people we do not know keep failing us, with consequences from Wall Street to the roadside stop.',
        'exactlywhattosay': 'Phil M. Jones delivers the precise phrases that move conversations forward, from &ldquo;How open-minded are you?&rdquo; to &ldquo;Just imagine.&rdquo; Our Most Useful Book of 2017.',
        'tedtalks': 'TED curator Chris Anderson&rsquo;s official guide to public speaking, drawn from the most-watched talks in the world. Our Most Useful Book of 2016.',
        'illuminate': 'Nancy Duarte and Patti Sanchez show leaders how to use speeches, stories, ceremonies and symbols to guide people through change they might otherwise resist.',
        'everybodywrites': 'Ann Handley&rsquo;s witty, endlessly practical handbook for creating ridiculously good content, built on the premise that in a digital world, everybody writes. Our Most Useful Book of 2014.',
        'pitchperfect': 'Media coach Bill McGowan shares the principles behind persuasion under pressure, from job interviews to television appearances.',
    },
}

CURATED['psychology'] = {
    'slug': 'best-psychology-books.html',
    'kicker': K,
    'h1': 'The Best Books On <br>Psychology &amp; Human <br>Behavior',
    'title': 'The Best Books On Psychology & Human Behavior | Non-Obvious Book Awards',
    'meta': ('The best books on psychology and human behavior — chosen from more than 800 books honored '
             'by the Non-Obvious Book Awards since 2014, from Atomic Habits to Stolen Focus.'),
    'intro': ('Why we think what we think, do what we do, and change (or fail to). From more than 800 '
              'books honored across a decade of the Non-Obvious Book Awards, these are the ones we most '
              'recommend on the strange, fascinating workings of the human mind.'),
    'badge': SEAL,
    'books': [
        ('2025', 'A Trick of the Mind', 'Daniel Yon', 'Longlist'),
        ('2025', 'Read Your Mind', 'Oz Pearlman', 'Shortlist'),
        ('2024', 'The Age of Magical Overthinking', 'Amanda Montell', 'Shortlist'),
        ('2024', 'Look Again', 'Tali Sharot and Cass R. Sunstein', 'Shortlist'),
        ('2023', 'Your Brain on Art', 'Susan Magsamen and Ivy Ross', 'Most Shareable Winner'),
        ('2023', 'Clear Thinking', 'Shane Parrish', 'Longlist'),
        ('2022', 'Stolen Focus', 'Johann Hari', 'Most Important Winner'),
        ('2022', 'Quit', 'Annie Duke', 'Most Shareable Winner'),
        ('2022', 'How Minds Change', 'David McRaney', 'Longlist'),
        ('2021', 'Think Again', 'Adam Grant', 'Most Useful Winner'),
        ('2021', 'Useful Delusions', 'Shankar Vedantam and Bill Mesler', 'Shortlist'),
        ('2020', 'Upstream', 'Dan Heath', 'Shortlist'),
        ('2019', 'Good Habits, Bad Habits', 'Wendy Wood', 'Longlist'),
        ('2018', 'Atomic Habits', 'James Clear', 'Shortlist'),
        ('2016', 'Grit', 'Angela Duckworth', 'Shortlist'),
        ('2014', 'The Confidence Code', 'Katty Kay and Claire Shipman', 'Most Important Winner'),
    ],
    'blurbs': {
        'atrickofthemind': 'Cognitive neuroscientist Daniel Yon reveals that the brain is less a camera than a prediction machine, constantly guessing at reality and usually getting away with it.',
        'readyourmind': 'Celebrity mentalist Oz Pearlman pulls back the curtain on how he reads people, turning his stage techniques into practical lessons in attention, connection and influence.',
        'theageofmagicaloverthinking': 'Amanda Montell examines the cognitive biases quietly running our modern lives, from celebrity worship to sunk costs, with wit and unusual honesty.',
        'lookagain': 'Tali Sharot and Cass Sunstein explain habituation: why we stop noticing what is constant, and how dishabituating can refresh everything from marriages to morality.',
        'yourbrainonart': 'Susan Magsamen and Ivy Ross gather the neuroscience showing that art and aesthetic experience measurably change our brains and bodies. Our Most Shareable Book of 2023.',
        'clearthinking': 'Farnam Street founder Shane Parrish shows that good judgment is less about intelligence and more about managing the defaults that hijack us in ordinary moments.',
        'stolenfocus': 'Johann Hari investigates why our attention is collapsing, and finds a dozen forces, most of them external, stealing our ability to think deeply. Our Most Important Book of 2022.',
        'quit': 'Former professional poker player Annie Duke makes the evidence-based case that walking away is a skill, and that knowing when to quit is the secret partner of grit. Our Most Shareable Book of 2022.',
        'howmindschange': 'David McRaney set out to learn how people abandon deeply held beliefs, and returns with a fascinating tour of deep canvassing, persuasion science and genuine open-mindedness.',
        'thinkagain': 'Adam Grant makes the case for the skill we need most and practice least: rethinking. Knowing what you do not know beats defending what you do. Our Most Useful Book of 2021.',
        'usefuldelusions': 'Hidden Brain host Shankar Vedantam explores the surprising upside of self-deception, and why some illusions hold lives, families and societies together.',
        'upstream': 'Dan Heath asks why we spend our lives reacting to problems we could have prevented, and profiles the people who moved upstream to stop trouble before it starts.',
        'goodhabitsbadhabits': 'Psychologist Wendy Wood brings three decades of original research on how habits actually form, and why willpower is the wrong tool for changing them.',
        'atomichabits': 'James Clear&rsquo;s system for getting one percent better every day, built on the compounding power of tiny changes. One of the most useful books of the decade by any measure.',
        'grit': 'Angela Duckworth&rsquo;s landmark research on why passion and perseverance predict success better than talent, and how grit can be grown.',
        'theconfidencecode': 'Katty Kay and Claire Shipman investigate the science and art of self-assurance, and why closing the confidence gap matters as much as competence. Our Most Important Book of 2014.',
    },
}
