"""Curated (hand-approved) topic page configs. Each book: (year_key, title, author, tag)."""

SEAL = 'assets/badges/web/seal-black.png'
K = 'Best Books Roundups'

CURATED = {
    'entrepreneurs': {
        'slug': 'best-books-for-entrepreneurs.html',
        'kicker': K,
        'h1': 'The Best Books For<br>Entrepreneurs Of<br>The Past Decade',
        'title': 'The Best Books For Entrepreneurs of the Past Decade | Non-Obvious Book Awards',
        'meta': ('The best books for entrepreneurs and startup founders of the past decade — chosen from more '
                 'than 800 books honored by the Non-Obvious Book Awards since 2014.'),
        'intro': ('From more than 800 books honored across a decade of the Non-Obvious Book Awards, these are '
                  'the ones we most recommend to founders and builders &mdash; on starting up, raising money, '
                  'negotiating, staying small on purpose, and surviving the messy middle.'),
        'badge': SEAL,
        'books': [
            ('2024', 'Pivot or Die', 'Gary Shapiro', 'Longlist'),
            ('2023', 'I Hope You Fail', 'Pinky Cole', 'Longlist'),
            ('2022', 'The Power Law', 'Sebastian Mallaby', 'Longlist'),
            ('2022', 'The Founders', 'Jimmy Soni', 'Longlist'),
            ('2021', 'Backable', 'Suneel Gupta', 'Shortlist'),
            ('2019', 'Company of One', 'Paul Jarvis', 'Longlist'),
            ('2019', 'Loonshots', 'Safi Bahcall', 'Shortlist'),
            ('2018', 'The Messy Middle', 'Scott Belsky', 'Longlist'),
            ('2018', 'Lost and Founder', 'Rand Fishkin', 'Longlist'),
            ('2017', 'Entrepreneurial You', 'Dorie Clark', 'Shortlist'),
            ('2016', 'Originals', 'Adam Grant', 'Shortlist'),
            ('2016', 'Never Split the Difference', 'Chris Voss', 'Shortlist'),
            ('2014', 'Hooked', 'Nir Eyal', 'Shortlist'),
        ],
        'blurbs': {
            'pivotordie': 'Consumer Technology Association CEO Gary Shapiro has watched thousands of companies rise and fall through CES &mdash; here he distills why the ability to pivot is the defining survival skill of any venture.',
            'ihopeyoufail': 'Slutty Vegan founder Pinky Cole flips every failure in her improbable rise into fuel &mdash; a raw, energizing playbook for entrepreneurs who will inevitably hit the wall.',
            'thepowerlaw': 'Sebastian Mallaby&rsquo;s definitive history of venture capital &mdash; how a handful of believers in outlier bets built the machine that finances nearly every startup dream.',
            'thefounders': 'Jimmy Soni&rsquo;s deeply reported story of the PayPal mafia &mdash; Musk, Thiel, Levchin and company &mdash; and the improbable beginnings of the network that shaped two decades of tech.',
            'backable': 'Suneel Gupta went from serial rejection to raising millions, and reverse-engineered why: people don&rsquo;t back ideas, they back people who make them believe. A founder&rsquo;s guide to being backable.',
            'companyofone': 'Paul Jarvis makes the liberating case that staying small is a strategy, not a failure &mdash; essential reading for every bootstrapper and solo founder.',
            'loonshots': 'Physicist-entrepreneur Safi Bahcall explains why organizations kill their wildest ideas &mdash; and the structures that let &ldquo;loonshots&rdquo; survive long enough to change the world.',
            'themessymiddle': 'Behance founder Scott Belsky maps the long, volatile stretch between starting and finishing that nobody talks about &mdash; and how to endure the lows and optimize the highs.',
            'lostandfounder': 'Moz founder Rand Fishkin&rsquo;s painfully honest field guide to startups &mdash; the anti-hype book every founder should read before raising a dollar.',
            'entrepreneurialyou': 'Dorie Clark&rsquo;s practical blueprint for building multiple income streams around your expertise &mdash; the book that launched a thousand portfolio careers.',
            'originals': 'Adam Grant on how non-conformists move the world &mdash; when to trust your instincts, how to champion new ideas, and why originality can be cultivated.',
            'neversplitthedifference': 'Former FBI lead hostage negotiator Chris Voss brings life-or-death negotiation tactics to business &mdash; arguably the most useful negotiation book ever written.',
            'hooked': 'Nir Eyal&rsquo;s four-step model for building habit-forming products &mdash; the framework behind a generation of product design.',
        },
    },
    'ai': {
        'slug': 'best-ai-books.html',
        'kicker': K,
        'h1': 'The Best Books On<br>Artificial<br>Intelligence',
        'title': 'The Best Books On Artificial Intelligence | Non-Obvious Book Awards',
        'meta': ('The best books on artificial intelligence — the AI books honored by the Non-Obvious Book '
                 'Awards, from AI Superpowers to Brave New Words, chosen from 800+ award entries.'),
        'intro': ('Artificial intelligence went from a niche topic to the defining story of our era &mdash; and '
                  'our awards lists tracked it the whole way. These are the best books on AI we have honored: '
                  'the optimists, the skeptics, the builders and the investigators.'),
        'badge': SEAL,
        'books': [
            ('2025', 'If Anyone Builds It, Everyone Dies', 'Eliezer Yudkowsky and Nate Soares', 'Longlist'),
            ('2025', 'Raising AI', 'De Kai', 'Longlist'),
            ('2024', 'Brave New Words', 'Salman Khan', 'Most Important Winner'),
            ('2024', 'The Worlds I See', 'Fei-Fei Li', 'Longlist'),
            ('2024', 'Genesis', 'Eric Schmidt', 'Longlist'),
            ('2024', 'The Singularity Is Nearer', 'Ray Kurzweil', 'Longlist'),
            ('2024', 'The Algorithm', 'Hilke Schellmann', 'Longlist'),
            ('2023', 'Unmasking AI', 'Joy Buolamwini', 'Shortlist'),
            ('2023', 'The Coming Wave', 'Mustafa Suleyman with Michael Bhaskar', 'Longlist'),
            ('2023', 'What Is ChatGPT Doing', 'Stephen Wolfram', 'Longlist'),
            ('2023', 'Your Face Belongs to Us', 'Kashmir Hill', 'Longlist'),
            ('2021', 'Futureproof', 'Kevin Roose', 'Shortlist'),
            ('2019', 'A Human Algorithm', 'Flynn Coleman', 'Longlist'),
            ('2018', 'AI Superpowers', 'Kai-Fu Lee', 'Longlist'),
        ],
        'blurbs': {
            'ifanyonebuildsiteveryonedies': 'The starkest case yet against racing to superintelligence &mdash; Yudkowsky and Soares argue, without hedging, that building smarter-than-human AI on our current path ends badly for everyone.',
            'raisingai': 'AI pioneer De Kai reframes our relationship with artificial intelligence as parenting &mdash; we are raising AI on our behavior, so we had better model well.',
            'bravenewwords': 'Khan Academy founder Salman Khan&rsquo;s hopeful, credible map of how AI will transform education &mdash; our Most Important Book of 2024.',
            'theworldsisee': 'Fei-Fei Li&rsquo;s luminous memoir of immigrating to America and helping invent modern AI &mdash; and her case for keeping humanity at its center.',
            'genesis': 'Eric Schmidt and co-authors on how AI reshapes power, statecraft and the human spirit &mdash; a geopolitical briefing for the intelligence age.',
            'thesingularityisnearer': 'Ray Kurzweil returns to his famous prediction with two decades of evidence &mdash; and argues the merge between humans and machines is closer than you think.',
            'thealgorithm': 'Investigative journalist Hilke Schellmann exposes the AI already deciding who gets hired, promoted and fired &mdash; often with no idea what it&rsquo;s doing.',
            'unmaskingai': 'Algorithmic Justice League founder Joy Buolamwini&rsquo;s account of discovering bias baked into facial recognition &mdash; and her fight to make AI accountable.',
            'thecomingwave': 'DeepMind co-founder Mustafa Suleyman on the containment problem: what happens when AI and synthetic biology outrun our ability to control them.',
            'whatischatgptdoing': 'Stephen Wolfram&rsquo;s remarkably clear explanation of what large language models actually do &mdash; still the best technical primer for curious non-engineers.',
            'yourfacebelongstous': 'Kashmir Hill&rsquo;s gripping investigation of Clearview AI and the secretive startup that ended anonymity &mdash; privacy journalism at its best.',
            'futureproof': 'Kevin Roose&rsquo;s nine rules for being human in the age of automation &mdash; practical optimism for anyone worried about the robots.',
            'ahumanalgorithm': 'Flynn Coleman&rsquo;s early, prescient exploration of how artificial intelligence forces us to redefine what makes us human &mdash; years before the ChatGPT era.',
            'aisuperpowers': 'Kai-Fu Lee&rsquo;s influential account of the AI race between Silicon Valley and China &mdash; the book that framed the geopolitics of AI.',
        },
    },
    'marketing': {
        'slug': 'best-marketing-books.html',
        'kicker': K,
        'h1': 'The Best Marketing<br>Books Of The<br>Past Decade',
        'title': 'The Best Marketing Books of the Past Decade | Non-Obvious Book Awards',
        'meta': ('The best marketing books of the past decade — the marketing, branding and persuasion books '
                 'honored by the Non-Obvious Book Awards since 2014.'),
        'intro': ('Marketing books were where the Non-Obvious Book Awards began &mdash; and across a decade of '
                  'lists we have honored the very best on branding, persuasion, storytelling and why things '
                  'catch on. These are the ones that still shape how the best marketers think.'),
        'badge': SEAL,
        'books': [
            ('2025', 'The Strategic Enemy', 'Laura Ries', 'Longlist'),
            ('2024', 'This Is Strategy', 'Seth Godin', 'Longlist'),
            ('2023', 'Magic Words', 'Jonah Berger', 'Longlist'),
            ('2023', 'For the Culture', 'Marcus Collins', 'Longlist'),
            ('2022', 'Influence Is Your Superpower', 'Zoe Chance', 'Longlist'),
            ('2020', 'The Catalyst', 'Jonah Berger', 'Longlist'),
            ('2019', 'Junior', 'Thomas Kemeny', 'Most Entertaining Winner'),
            ('2019', 'Stories That Stick', 'Kindra Hall', 'Longlist'),
            ('2019', 'Alchemy', 'Rory Sutherland', 'Shortlist'),
            ('2018', 'This Is Marketing', 'Seth Godin', 'Longlist'),
            ('2018', 'Talk Triggers', 'Jay Baer and Daniel Lemin', 'Shortlist'),
            ('2017', 'Hit Makers', 'Derek Thompson', 'Shortlist'),
            ('2017', 'Your Ad Ignored Here', 'Tom Fishburne', 'Shortlist'),
            ('2016', 'Small Data', 'Martin Lindstrom', 'Most Shareable Winner'),
            ('2016', 'Invisible Influence', 'Jonah Berger', 'Shortlist'),
            ('2014', 'Everybody Writes', 'Ann Handley', 'Most Useful Winner'),
        ],
        'blurbs': {
            'thestrategicenemy': 'Positioning heir Laura Ries argues every great brand needs an enemy &mdash; a sharp modern update to the playbook her father helped invent.',
            'thisisstrategy': 'Seth Godin distills a lifetime of thinking into a book about systems, games and time &mdash; strategy for people who want to make change happen.',
            'magicwords': 'Jonah Berger reveals the specific words that convince, engage and persuade &mdash; backed by natural language research on millions of interactions.',
            'fortheculture': 'Marcus Collins &mdash; the strategist behind campaigns for Beyonc&eacute; and McDonald&rsquo;s &mdash; on why culture is the most powerful force in marketing, and how brands earn a place in it.',
            'influenceisyoursuperpower': 'Yale professor Zoe Chance turns her famous MBA course into a warm, science-backed guide to becoming more influential without being manipulative.',
            'thecatalyst': 'Jonah Berger flips persuasion on its head: stop pushing harder and start removing the barriers that keep people from changing their minds.',
            'junior': 'Thomas Kemeny&rsquo;s irreverent, genuinely useful guide to making it in advertising &mdash; our Most Entertaining Book of 2019, and the funniest career book we&rsquo;ve ever honored.',
            'storiesthatstick': 'Kindra Hall&rsquo;s four essential story frameworks for business &mdash; the practical bridge between &ldquo;storytelling matters&rdquo; and actually doing it.',
            'alchemy': 'Ogilvy vice chairman Rory Sutherland&rsquo;s gleeful case for magic over logic &mdash; why the irrational ideas are so often the ones that work.',
            'thisismarketing': 'Seth Godin&rsquo;s modern manifesto: marketing as the generous act of helping people solve their problems &mdash; the antidote to interruption-era thinking.',
            'talktriggers': 'Jay Baer and Daniel Lemin show how to build operational differentiators that customers can&rsquo;t stop talking about &mdash; word of mouth, engineered on purpose.',
            'hitmakers': 'Derek Thompson&rsquo;s science of popularity &mdash; why some products and ideas take off while equally good ones vanish. Distribution has never been explained better.',
            'youradignoredhere': 'Marketoonist Tom Fishburne skewers marketing&rsquo;s absurdities in cartoons that are funny because they&rsquo;re true &mdash; and wiser than most strategy decks.',
            'smalldata': 'Brand detective Martin Lindstrom shows how tiny human clues &mdash; a worn sneaker, a fridge magnet &mdash; reveal desires that big data completely misses.',
            'invisibleinfluence': 'Jonah Berger on the hidden social forces that shape every choice we make &mdash; including the ones we&rsquo;re sure we made on our own.',
            'everybodywrites': 'Ann Handley&rsquo;s field guide to creating ridiculously good content &mdash; our Most Useful Book winner, and still the standard for anyone who writes for business.',
        },
    },
    'productivity': {
        'slug': 'best-productivity-books.html',
        'kicker': K,
        'h1': 'The Best Productivity<br>Books Of The<br>Past Decade',
        'title': 'The Best Productivity Books of the Past Decade | Non-Obvious Book Awards',
        'meta': ('The best productivity books of the past decade — the books on habits, focus and getting '
                 'things done honored by the Non-Obvious Book Awards since 2014.'),
        'intro': ('A decade of our award lists produced a small shelf of books that actually change how people '
                  'work &mdash; on habits, focus, timing, learning and doing less, better. These are the '
                  'productivity books we keep recommending, year after year.'),
        'badge': SEAL,
        'books': [
            ('2025', 'Reset', 'Dan Heath', 'Longlist'),
            ('2024', 'Slow Productivity', 'Cal Newport', 'Longlist'),
            ('2024', 'Uptime', 'Laura Mae Martin', 'Longlist'),
            ('2023', 'Clear Thinking', 'Shane Parrish', 'Longlist'),
            ('2023', 'The PARA Method', 'Tiago Forte', 'Longlist'),
            ('2022', 'Stolen Focus', 'Johann Hari', 'Most Important Winner'),
            ('2021', 'Subtract', 'Leidy Klotz', 'Shortlist'),
            ('2019', 'Good Habits, Bad Habits', 'Wendy Wood', 'Longlist'),
            ('2019', 'Digital Minimalism', 'Cal Newport', 'Longlist'),
            ('2019', 'Indistractable', 'Nir Eyal', 'Longlist'),
            ('2019', 'Ultralearning', 'Scott H. Young', 'Shortlist'),
            ('2018', 'Atomic Habits', 'James Clear', 'Shortlist'),
            ('2018', 'When', 'Daniel H. Pink', 'Shortlist'),
            ('2017', 'Finish', 'Jon Acuff', 'Longlist'),
        ],
        'blurbs': {
            'reset': 'Dan Heath on finding the leverage points where a little effort changes everything &mdash; how to get unstuck and make work actually work.',
            'slowproductivity': 'Cal Newport&rsquo;s antidote to pseudo-productivity: do fewer things, work at a natural pace, and obsess over quality.',
            'uptime': 'Google&rsquo;s executive productivity advisor Laura Mae Martin shares the system she teaches the company&rsquo;s leaders &mdash; calm, practical and immediately usable.',
            'clearthinking': 'Farnam Street&rsquo;s Shane Parrish on mastering the ordinary moments that determine extraordinary outcomes &mdash; judgment as a trainable skill.',
            'theparamethod': 'Tiago Forte&rsquo;s elegantly simple system for organizing your entire digital life &mdash; four folders that end the chaos.',
            'stolenfocus': 'Johann Hari&rsquo;s investigation into why the world stopped paying attention &mdash; our Most Important Book of 2022, and the deepest treatment of focus ever honored on our lists.',
            'subtract': 'Engineer Leidy Klotz on the untapped science of less &mdash; why our instinct is always to add, and what becomes possible when we subtract instead.',
            'goodhabitsbadhabits': 'Habit science&rsquo;s leading researcher Wendy Wood explains what forty years of evidence actually says about how habits form and break.',
            'digitalminimalism': 'Cal Newport&rsquo;s philosophy for reclaiming attention in a noisy world &mdash; the book that launched a thousand digital declutters.',
            'indistractable': 'Hooked author Nir Eyal turns his knowledge of habit-forming tech against distraction itself &mdash; how to control your attention and choose your life.',
            'ultralearning': 'Scott Young &mdash; who completed MIT&rsquo;s computer science curriculum in a year on his own &mdash; shares the strategy of aggressive self-directed learning.',
            'atomichabits': 'James Clear&rsquo;s modern classic on how tiny changes compound into remarkable results &mdash; the best-selling productivity book of its generation, honored on our 2018 shortlist.',
            'when': 'Daniel Pink turns timing into a science &mdash; when to work, when to break, when to switch &mdash; and proves that when you do things matters as much as what you do.',
            'finish': 'Jon Acuff&rsquo;s funny, liberating case that perfectionism &mdash; not laziness &mdash; is why we don&rsquo;t finish things, and how to beat it.',
        },
    },
    'memoirs': {
        'slug': 'best-business-memoirs.html',
        'kicker': K,
        'h1': 'The Best Business<br>Memoirs Of The<br>Past Decade',
        'title': 'The Best Business Memoirs of the Past Decade | Non-Obvious Book Awards',
        'meta': ('The best business memoirs of the past decade — first-person stories from founders and CEOs '
                 'honored by the Non-Obvious Book Awards since 2014.'),
        'intro': ('The best business books are sometimes the ones where somebody lived it. From a decade of our '
                  'award lists, these are the memoirs we most recommend &mdash; founders, CEOs and insiders '
                  'telling the truth about what building, leading and surviving really looks like.'),
        'badge': SEAL,
        'books': [
            ('2025', 'Careless People', 'Sarah Wynn-Williams', 'Most Shareable Winner'),
            ('2025', 'Bag Man', 'Lew Frankfort', 'Longlist'),
            ('2025', 'Change the Recipe', 'José Andrés with Richard Wolffe', 'Longlist'),
            ('2023', 'Turnaround Time', 'Oscar Munoz', 'Longlist'),
            ('2023', 'Black Founder', 'Stacy Spikes', 'Longlist'),
            ('2021', 'Becoming Trader Joe', 'Joe Coulombe with Patty Civalleri', 'Longlist'),
            ('2021', 'Play Nice But Win', 'Michael Dell', 'Longlist'),
            ('2019', 'This Is Not a T-Shirt', 'Bobby Hundreds', 'Longlist'),
            ('2019', "It's How We Play the Game", 'Ed Stack', 'Longlist'),
            ('2019', 'Wise Guy', 'Guy Kawasaki', 'Longlist'),
            ('2018', 'Imagine It Forward', 'Beth Comstock', 'Longlist'),
            ('2017', 'Reset', 'Ellen Pao', 'Longlist'),
            ('2017', 'Hit Refresh', 'Satya Nadella', 'Most Shareable Winner'),
            ('2016', 'Disrupted', 'Dan Lyons', 'Most Entertaining Winner'),
        ],
        'blurbs': {
            'carelesspeople': 'Sarah Wynn-Williams&rsquo;s explosive insider memoir of life among Facebook&rsquo;s leadership &mdash; our Most Shareable Book of 2025, and the book everyone in tech spent the year talking about.',
            'bagman': 'Lew Frankfort&rsquo;s account of taking Coach from a $6 million family workshop to a global luxury powerhouse &mdash; a masterclass in brand-building told first-hand.',
            'changetherecipe': 'Chef Jos&eacute; Andr&eacute;s serves up the lessons of a life spent cooking, building restaurants and feeding people in crisis &mdash; generosity as a business philosophy.',
            'turnaroundtime': 'Oscar Munoz&rsquo;s story of turning around United Airlines while surviving a heart transplant &mdash; leadership under the most literal pressure imaginable.',
            'blackfounder': 'MoviePass founder Stacy Spikes on building companies as a Black founder in tech and Hollywood &mdash; candid about the doors that opened, and the ones that didn&rsquo;t.',
            'becomingtraderjoe': 'Joe Coulombe&rsquo;s own account of inventing America&rsquo;s most beloved grocery store &mdash; contrarian retail wisdom from the man who did everything differently.',
            'playnicebutwin': 'Michael Dell&rsquo;s unvarnished telling of the fights that defined his company &mdash; going private, battling Carl Icahn, and betting the business twice.',
            'thisisnotatshirt': 'Bobby Hundreds on building streetwear brand The Hundreds &mdash; the definitive book on community-first brand building, from someone who lived it.',
            'itshowweplaythegame': 'Dick&rsquo;s Sporting Goods CEO Ed Stack on building a retail giant &mdash; and the decision to pull assault-style rifles off his shelves, whatever it cost.',
            'wiseguy': 'Guy Kawasaki&rsquo;s life in stories &mdash; from evangelizing the Macintosh to surfing at sixty &mdash; told with the warmth and candor of tech&rsquo;s original evangelist.',
            'imagineitforward': 'Beth Comstock on two decades of championing change inside GE &mdash; an honest look at what innovation actually costs inside a giant company.',
            'reset': 'Ellen Pao&rsquo;s account of her discrimination suit against Kleiner Perkins and what it revealed about Silicon Valley &mdash; the memoir that helped spark tech&rsquo;s reckoning.',
            'hitrefresh': 'Satya Nadella&rsquo;s inside account of transforming Microsoft by putting empathy at the center of one of the world&rsquo;s most powerful companies.',
            'disrupted': 'Dan Lyons&rsquo;s riotous memoir of going from Newsweek to a tech startup at age 50 &mdash; still the funniest and sharpest book ever written about startup culture.',
        },
    },
}

CURATED['southasian'] = {
    'slug': 'best-books-south-asian-authors.html',
    'kicker': 'Best Books Roundups',
    'h1': 'Best Award Winning<br>Business Books From<br>South Asian Authors',
    'title': 'Best Award Winning Business Books From South Asian Authors | Non-Obvious Book Awards',
    'meta': ('The best award-winning business and non-fiction books by South Asian authors, honored by the '
             'Non-Obvious Book Awards since 2014, listed alphabetically by author.'),
    'intro': ('A decade of the Non-Obvious Book Awards has honored an extraordinary group of South Asian '
              'authors, from CEOs and surgeons general to linguists, economists and entrepreneurs. Collected '
              'here in one reading list, alphabetically by author: every one of their honored books.'),
    'badge': 'assets/badges/web/seal-black.png',
    'books': [
        ('2018', 'Belong', 'Radha Agrawal', 'Longlist'),
        ('2024', 'Nuts and Bolts', 'Roma Agrawal', 'Longlist'),
        ('2022', 'Go Back to Where You Came From', 'Wajahat Ali', 'Longlist'),
        ('2024', 'How to Win Friends and Influence Fungi', 'Chris Balakrishnan', 'Longlist'),
        ('2022', 'The Titanium Economy', 'Asutosh Padhi and Gaurav Batra', 'Longlist'),
        ('ideapress', 'Non-Obvious Thinking', 'Rohit Bhargava', '!Published By Ideapress (Not Eligible For Awards)'),
        ('2025', 'The 5 Types of Wealth', 'Sahil Bloom', 'Longlist'),
        ('2022', 'The Newlyweds', 'Mansi Choksi', 'Longlist'),
        ('2020', 'The Person You Mean to Be', 'Dolly Chugh', 'Longlist'),
        ('2021', 'Digital Body Language', 'Erica Dhawan', 'Longlist'),
        ('2018', 'Winners Take All', 'Anand Giridharadas', 'Most Original Winner'),
        ('2025', 'How to Be Bold', 'Ranjay Gulati', 'Longlist'),
        ('2021', 'Backable', 'Suneel Gupta', 'Shortlist'),
        ('2024', 'Breaking Bias', 'Anu Gupta', 'Longlist'),
        ('2023', 'Win Every Argument', 'Mehdi Hasan', 'Longlist'),
        ('2025', 'Make Art', 'Nishant Jain', 'Longlist'),
        ('2017', 'Give Work', 'Leila Janah', 'Most Important Winner'),
        ('2021', 'Peak Mind', 'Amishi P. Jha', 'Longlist'),
        ('2024', 'Brave New Words', 'Salman Khan', 'Most Important Winner'),
        ('2021', 'Move', 'Parag Khanna', 'Most Shareable Winner'),
        ('2022', 'The 6 Phase Meditation Method', 'Vishen Lakhiani', 'Longlist'),
        ('2024', 'Wicked Problems', 'Guru Madhavan', 'Longlist'),
        ('2025', 'Uncompete', 'Ruchika T. Malhotra', 'Longlist'),
        ('2025', 'The Devil Emails at Midnight', 'Mita Mallick', 'Longlist'),
        ('2021', 'Fast Company Innovation by Design', 'Stephanie Mehta', 'Longlist'),
        ('2017', 'The Power of Onlyness', 'Nilofer Merchant', 'Longlist'),
        ('2020', 'Together', 'Vivek H. Murthy', 'Shortlist'),
        ('2017', 'Hit Refresh', 'Satya Nadella', 'Most Shareable Winner'),
        ('2025', "You're the Boss", 'Sabina Nawaz', 'Longlist'),
        ('2018', 'The Art of Gathering', 'Priya Parker', 'Shortlist'),
        ('2023', 'The Power of Saying No', 'Vanessa Patrick', 'Longlist'),
        ('2021', "You Can't Be Serious", 'Kal Penn', 'Longlist'),
        ('2023', 'The Future Is Disabled', 'Leah Lakshmi Piepzna-Samarasinha', 'Longlist'),
        ('2016', 'Persuadable', 'Al Pittampalli', 'Most Important Winner'),
        ('ideapress', 'Good Awkward', 'Henna Pryor', '!Published By Ideapress (Not Eligible For Awards)'),
        ('2022', 'The First, the Few, the Only', 'Deepa Purushothaman', 'Longlist'),
        ('2023', 'Upshift', 'Ben Ramalingam', 'Longlist'),
        ('2025', 'Defy', 'Sunita Sah', 'Longlist'),
        ('2023', 'Big Bets', 'Rajiv Shah', 'Longlist'),
        ('2023', 'The Defiant Optimist', 'Durreen Shahnaz', 'Longlist'),
        ('2024', 'Math Mind', 'Shalinee Sharma', 'Longlist'),
        ('2017', 'How To Be A Bawse', 'Lilly Singh', 'Shortlist'),
        ('2022', 'The Light We Give', 'Simran Jeet Singh', 'Longlist'),
        ('ideapress', 'Savvy', 'Shiv Singh and Rohini Luthra', '!Published By Ideapress (Not Eligible For Awards)'),
        ('ideapress', 'Why It Hurts', 'Aneesh Singla', '!Published By Ideapress (Not Eligible For Awards)'),
        ('2022', 'The Founders', 'Jimmy Soni', 'Longlist'),
        ('2025', 'Rethinking Work', 'Rishad Tobaccowala', 'Longlist'),
        ('2021', 'Useful Delusions', 'Shankar Vedantam', 'Shortlist'),
        ('2019', "The Optimist's Telescope", 'Bina Venkataraman', 'Longlist'),
        ('2020', 'Ten Lessons for a Post-Pandemic World', 'Fareed Zakaria', 'Longlist'),
        ('2024', 'Hope for Cynics', 'Jamil Zaki', 'Longlist'),
    ],
    'blurbs': {
        'belong': 'Daybreaker founder Radha Agrawal turns community-building into a practical craft: how to find your people, or gather them yourself.',
        'nutsandbolts': 'Structural engineer Roma Agrawal breaks the built world down to seven tiny inventions, from the nail to the spring, and finds wonder in each one.',
        'gobacktowhereyoucamefrom': 'Wajahat Ali answers a lifetime of that question with humor and heart: a memoir of growing up Muslim American that disarms hate by out-charming it.',
        'howtowinfriendsandinfluencefungi': 'Nerd Nite co-founder Chris Balakrishnan collects the wildest, funniest science talks from the beloved lecture series. Learning disguised as a night out.',
        'thetitaniumeconomy': 'McKinsey&rsquo;s Asutosh Padhi and Gaurav Batra spotlight the industrial-tech companies quietly powering American prosperity, hiding in plain sight.',
        'nonobviousthinking': 'From our founder, with Ben DuPont: a field guide to seeing what others miss, in four practiced habits. The thinking behind everything we do here.',
        'the5typesofwealth': 'Sahil Bloom reframes rich across five kinds of wealth: time, social, mental, physical and financial. A generational bestseller about what actually counts.',
        'thenewlyweds': 'Mansi Choksi follows three young Indian couples who married for love against every expectation, and pays close attention to what it cost them.',
        'thepersonyoumeantobe': 'NYU psychologist Dolly Chugh replaces the pressure of being a good person with the freedom of being a good-ish one: growth over perfection in the fight for fairness.',
        'digitalbodylanguage': 'Erica Dhawan decodes the signals we send on screens, where tone is invisible and a period can read as anger. Essential for the hybrid work era.',
        'winnerstakeall': 'Anand Giridharadas&rsquo;s unsparing look at how the global elite&rsquo;s world-changing efforts often protect the very systems that created the problems. A book that reframed an entire debate.',
        'howtobebold': 'Harvard Business School&rsquo;s Ranjay Gulati studies people who act with courage when it counts, and shows that boldness is a skill you can train.',
        'backable': 'Suneel Gupta went from serial rejection to raising millions, then reverse-engineered why: people don&rsquo;t back ideas, they back people who make them believe.',
        'breakingbias': 'Scientist and lawyer Anu Gupta offers research-backed practices for interrupting bias, in our minds and in our institutions, without shame or blame.',
        'wineveryargument': 'Broadcaster Mehdi Hasan shares the rhetorical craft behind his famous interviews: how to persuade, debate and hold your own in any room.',
        'makeart': 'SneakyArt creator Nishant Jain gives readers permission to draw: art as a daily practice of noticing the world, no talent prerequisite required.',
        'givework': 'Samasource founder Leila Janah argues the surest way to end global poverty is not charity but work, and shows how giving work transforms lives and communities.',
        'peakmind': 'Neuroscientist Amishi Jha shows that attention is trainable: twelve minutes a day of practice measurably strengthens focus, even under extreme stress.',
        'bravenewwords': 'Khan Academy founder Salman Khan offers the most credible early map of how AI will transform how our kids learn, and why that future is more hopeful than we fear.',
        'move': 'Parag Khanna maps the forces of climate, economics and demographics that will make the next decades the most mobile in human history, and predicts where we will all go.',
        'the6phasemeditationmethod': 'Mindvalley founder Vishen Lakhiani engineers meditation for people who hate sitting still: six phases, a few minutes, built for performance.',
        'wickedproblems': 'National Academy of Engineering&rsquo;s Guru Madhavan celebrates the unglamorous engineering mindset that untangles society&rsquo;s messiest, most wicked problems.',
        'uncompete': 'Ruchika T. Malhotra makes the case for dropping zero-sum thinking at work: collaboration, not competition, is the real advantage.',
        'thedevilemailsatmidnight': 'Mita Mallick turns years of surviving difficult bosses into a survival guide for the rest of us, without becoming the villain yourself.',
        'fastcompanyinnovationbydesign': 'Fast Company&rsquo;s Stephanie Mehta showcases two decades of design that changed business, proof that how things look and work is strategy.',
        'thepowerofonlyness': 'Nilofer Merchant names the source of every big idea: your onlyness, the singular spot where only you stand. Then she shows how to scale it.',
        'together': 'Former Surgeon General Vivek Murthy diagnoses loneliness as a public health crisis and prescribes the connection our bodies literally require.',
        'hitrefresh': 'Satya Nadella&rsquo;s inside account of transforming Microsoft by putting empathy at the center of one of the world&rsquo;s most powerful companies.',
        'youretheboss': 'Executive coach Sabina Nawaz reveals how power quietly changes managers, and the habits that keep new bosses effective and human.',
        'theartofgathering': 'Priya Parker transforms how we think about meetings, parties and conferences: every gathering needs a purpose, and most of ours have none.',
        'thepowerofsayingno': 'Professor Vanessa Patrick shares the science of empowered refusal: how to say no without guilt, and why it is a superpower at work.',
        'youcantbeserious': 'Kal Penn&rsquo;s funny, improbable memoir of chasing two careers at once: Hollywood actor and White House staffer. Proof that permission is overrated.',
        'thefutureisdisabled': 'Leah Lakshmi Piepzna-Samarasinha imagines futures built on disability justice, where care is collective and no one is disposable.',
        'persuadable': 'Al Pittampalli makes the counterintuitive case that the willingness to change your mind, being persuadable, is a defining strength of modern leadership.',
        'goodawkward': 'Executive coach Henna Pryor rebrands awkwardness as a professional asset: the discomfort you avoid is exactly where your edge lives.',
        'thefirstthefewtheonly': 'Deepa Purushothaman draws on hundreds of interviews with women of color in corporate America: the tolls, the tactics and the power in numbers.',
        'upshift': 'Ben Ramalingam studies people who perform best under pressure and distills the science of turning stress and adversity into fuel.',
        'defy': 'Psychologist Sunita Sah studies why good people comply when they long to resist, and teaches defiance as a principled, learnable skill.',
        'bigbets': 'Rockefeller Foundation president Rajiv Shah argues incrementalism is overrated: the biggest global problems yield only to big bets.',
        'thedefiantoptimist': 'Durreen Shahnaz, the first Bangladeshi woman on Wall Street&rsquo;s trading floor, tells how she built a financial platform for the world&rsquo;s excluded.',
        'mathmind': 'Zearn CEO Shalinee Sharma dismantles the myth of the math person: everyone can love math when it is taught the way brains actually learn.',
        'howtobeabawse': 'YouTube superstar Lilly Singh&rsquo;s no-excuses guide to conquering life, told with the hustle and humor that built her from bedroom vlogger to global entertainer.',
        'thelightwegive': 'Simran Jeet Singh shares Sikh wisdom for living with connection and courage in divided times. A book of practical grace.',
        'savvy': 'Shiv Singh and Rohini Luthra deliver a field guide to navigating fake companies, fake leaders and fake news, and staying clear-eyed in a post-trust era.',
        'whyithurts': 'Physician Aneesh Singla reframes pain as the body&rsquo;s essential messenger: what it is for, why we need it, and how understanding it changes treatment.',
        'thefounders': 'Jimmy Soni&rsquo;s deeply reported story of the PayPal mafia, and the improbable beginnings of the network that shaped two decades of tech.',
        'rethinkingwork': 'Advertising sage Rishad Tobaccowala maps the four seismic shifts remaking work, and how to build a career that thrives through all of them.',
        'usefuldelusions': 'Hidden Brain host Shankar Vedantam makes the counterintuitive case that self-deception is not always a bug: some illusions hold lives and societies together.',
        'theoptimiststelescope': 'Bina Venkataraman, former White House climate adviser, on why we are so bad at thinking ahead, and the tools that give foresight a fighting chance.',
        'tenlessonsforapostpandemicworld': 'Fareed Zakaria distills what the pandemic revealed about globalization, government and risk into ten clear-eyed lessons for what comes next.',
        'hopeforcynics': 'Stanford psychologist Jamil Zaki brings the evidence against cynicism: hopeful skepticism is more accurate, more useful and better for us.',
    },
}
